language: php
 
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
 
install:
  - composer self-update
  - composer require satooshi/php-coveralls:^1.0
  - composer require squizlabs/php_codesniffer:^2.7
  - composer require codeclimate/php-test-reporter:^0.3.2
  - composer install --no-interaction
  - composer show
 
script:
  - composer validate --strict
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - ./vendor/bin/phpcs --standard=PSR2 src tests
  # if xdebug isn't enabled, test-reporter will fail and the build will fail...
  - if [[ "$(php --version | grep -cim1 xdebug)" -ge 1 ]]; then ./vendor/bin/test-reporter; fi
  - cat /home/travis/build/whatsma/ZodiacSign/vendor/codeclimate/php-test-reporter/composer/bin/test-reporter


after_script:
  - ./vendor/bin/coveralls -v

notifications:
  email:
    on_success: always
    on_failure: always
